version: '3'
services:
    db:
        build:
            context: ./mariadb
            dockerfile: dockerfile
        restart: unless-stopped
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        environment:
            MARIADB_ROOT_PASSWORD: password
            MARIADB_USER: dbadmin
            MARIADB_PASSWORD: password
            MARIADB_DATABASE: employee
        volumes:
            - db_data:/var/lib/mysql
#            - ./mariadb/mysqldump:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"
    phpmyadmin:
        image: phpmyadmin
        restart: unless-stopped
        depends_on: 
            - db
        environment:
            - PMA_HOSTS=db
        ports:
            - "5555:80"
    backend:
        build: ./backend
        restart: unless-stopped
        depends_on: 
            - db
        ports:
            - "3001:3001"
    frontend:
        build: ./frontend
        restart: unless-stopped
        depends_on:
            - backend
        ports:
            - "3000:80"
volumes:
    db_data:

networks:
  default:
    external: true
    name: tuxtum
